/* A standard layout for the Dactyl Manuform 5x6 Keyboard */ 

#include QMK_KEYBOARD_H


#define _QWERTY 0
#define _LOWER 1
#define _RAISE 2

#define RAISE MO(_RAISE)
#define LOWER MO(_LOWER)

#ifdef OLED_DRIVER_ENABLE
#define OLED_DISPLAY_128X64
#define OLED_IC OLED_IC_SSD1306
void oled_task_user(void) {
    // Host Keyboard Layer Status
    oled_write_P(PSTR("Layer: "), false);

    switch (get_highest_layer(layer_state)) {
        case _QWERTY:
            oled_write_P(PSTR("Default\n"), false);
            break;
        case _LOWER:
            oled_write_P(PSTR("LOWER\n"), false);
            break;
        case _RAISE:
            oled_write_P(PSTR("RAISE\n"), false);
            break;
        default:
            // Or use the write_ln shortcut over adding '\n' to the end of your string
            oled_write_ln_P(PSTR("Undefined"), false);
    }

    // Host Keyboard LED Status
    led_t led_state = host_keyboard_led_state();
    oled_write_P(led_state.num_lock ? PSTR("NUM ") : PSTR("    "), false);
    oled_write_P(led_state.caps_lock ? PSTR("CAP ") : PSTR("    "), false);
    oled_write_P(led_state.scroll_lock ? PSTR("SCR ") : PSTR("    "), false);
}
#endif
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  // If console is enabled, it will print the matrix position and status of each key pressed
#ifdef CONSOLE_ENABLE
    uprintf("KL: kc: %u, col: %u, row: %u, pressed: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed);
#endif 
  return true;
}
void keyboard_post_init_user(void) {
  // Customise these values to desired behaviour
  debug_enable=true;
  debug_matrix=true;
  //debug_keyboard=true;
  //debug_mouse=true;
}


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#define LAYOUT_ergodox(\
  L00, L01, L02, L03, L04, L05, L06,\
  L10, L11, L12, L13, L14, L15, L16,\
  L20, L21, L22, L23, L24, L25,\
  L30, L31, L32, L33, L34, L35,L36,\
     L40, L41, L42, L43, L44, \
                               L07,L17,\
                           L45,L46,L27,\
                                   L37,\
R50, R51, R52, R53, R54, R55, R56,\
R60, R61, R62, R63, R64, R65, R66,\
     R70, R71, R72, R73, R74, R75,\
R80, R81, R82, R83, R84, R85,R86, \
          R90, R91, R92, R93, R94,          \
\
R67,R57,\
R77,R96,R95,\
R87\
   ) \
  { \
    { L00,   L01,   L02, L03, L04, L05, L06,  L07   }, \
    { L10,   L11,   L12, L13, L14, L15, L16,  L17   }, \
    { L20,   L21,   L22, L23, L24, L25, KC_NO,L27   }, \
    { L30,   L31,   L32, L33, L34, L35, L36,  L37   }, \
    { L40,   L41,   L42, L43, L44, L45, L46,  KC_NO }, \
\
    { R56, R55, R54, R53, R52, R51, R50, R57 }, \
    { R66, R65, R64, R63, R62, R61, R60, R67 },\
    { R75, R74, R73, R72, R71, R70, KC_NO, R77 }, \
    { R86, R85, R84, R83, R82, R81, R80, R87 }, \
    { R94, R93, R92, R91, R90, R95, R96, KC_NO} \
}
/*    { R00, R01, R02, R03, R04,   R05, R06,   R07   }, \
//    { R10, R11, R12, R13, R14,   R15, R16,m   R17   }, \
//    { R20, R21, R22, R23, R24,   R25, KC_NO, R27   }, \
//    { R30, R31, R32, R33, R34,   R35, R36,   R37   }, \
//    { R40, R41, R42, R43, R44,   R45, R46,   KC_NO }, \
*/



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox(
        KC_ESC,  KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, 
	KC_TAB,  KC_Q, KC_W, KC_E, KC_R, KC_T, TT(2), 
	KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, 
	KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, TT(1), 
	KC_LCTL, KC_LALT, KC_QUOT, KC_LBRC, KC_RBRC, 
	                        KC_LALT, KC_LGUI,
                       KC_SPC,  KC_ENT,  KC_HOME,
                                         KC_END,

	KC_7,  KC_8, KC_9, KC_0, KC_EQL, KC_MINS, KC_BSPC, 
        KC_LBRC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, 
                 KC_H, KC_J, KC_K, KC_L, KC_QUOT,KC_ENT,
        KC_DEL, KC_N, KC_M, KC_SCLN, KC_SLSH, KC_UP, KC_RSFT, 
        KC_COMM, KC_DOT, KC_LEFT, KC_DOWN, KC_RGHT, 
  
         KC_RGUI, KC_RALT, 
         KC_PGUP, KC_ENT, KC_SPC,
         KC_PGDN),

    	[1] = LAYOUT_ergodox(
	KC_TRNS, KC_F1,   KC_F2,  KC_F3,   KC_F4,   KC_F5,   KC_F6, 
	KC_TRNS, KC_EXLM, KC_AT,  KC_LCBR, KC_RCBR, KC_PIPE, KC_TRNS, 
	         KC_TRNS, KC_HASH, KC_DLR, KC_LPRN, KC_RPRN, KC_GRV,  
        KC_TRNS, KC_PERC, KC_CIRC, KC_LBRC, KC_RBRC, KC_TILD, KC_TRNS, 
        EEP_RST, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
                   BL_TOGG, KC_TRNS, 
          KC_TRNS, BL_INC, BL_DEC, 
                           KC_TRNS, 
        KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, 
        KC_TRNS, KC_PEQL, KC_7, KC_8, KC_9, KC_ASTR, KC_TRNS, 
                 KC_TRNS, KC_4, KC_5, KC_6, KC_PLUS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_1, KC_2, KC_3, KC_TRNS, KC_TRNS, 
        KC_0, KC_PDOT, KC_TRNS, KC_TRNS, KC_TRNS, 
                   KC_TRNS, KC_TRNS, 
          KC_TRNS, KC_TRNS, KC_TRNS, 
                            KC_TRNS),
	[2] = LAYOUT_ergodox(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_U, KC_TRNS, KC_TRNS, KC_TRNS, 
                 KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_BTN2, 
                   KC_TRNS, KC_TRNS, 
          KC_TRNS, KC_TRNS, KC_TRNS, 
                            KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_MNXT, KC_TRNS, KC_TRNS, 
        KC_VOLU, KC_VOLD, KC_MUTE, KC_TRNS, KC_TRNS, 
                   KC_TRNS, KC_TRNS, 
          KC_TRNS, KC_TRNS, KC_TRNS, 
                            KC_WBAK)
};
