#include "macro_num_pad_pro.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT(
		KC_P7, KC_P8, KC_P9, KC_PPLS,KC_MUTE,TG(1),
		KC_P4, KC_P5, KC_P6, KC_PMNS,
		KC_P1, KC_P2, KC_P3, KC_P0,
		KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F11,
		KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F12,
		KC_HOME, KC_UP, KC_END, KC_UP, KC_INS, KC_PSLS,
		KC_LEFT, KC_DOWN, KC_RIGHT, KC_DOWN, KC_PAST, KC_PENT),
	[1] = LAYOUT(
		BL_TOGG, BL_INC, BL_DEC, KC_F4,KC_TRNS,KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT(
		BL_ON, BL_INC, BL_DEC, KC_F4,KC_TRNS,KC_TRNS,
		KC_F5, KC_F6, KC_F7, KC_F8,
		KC_F9, KC_F10, KC_F11, KC_F12,
		KC_PPLS, KC_PSLS, KC_PAST, KC_PMNS, KC_BSPC, KC_HOME,
		KC_P7, KC_P8, KC_P9, KC_P0, KC_PDOT, KC_END,
		KC_P4, KC_P5, KC_P6, KC_UP, KC_PEQL, KC_PGUP,
		KC_P1, KC_P2, KC_P3, KC_DOWN, KC_RGHT, KC_PGDN)
};

